[project]
name = "mar-12-2025-pbt2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "hypothesis>=6.129.0",
    "pytest>=8.3.5",
]
